print("--- BANKING QA ---")
print("Minimum/Maximum Age: PASS")
print("Invalid Salary: PASS")
print("Poor Credit Score: PASS")
print("Existing Loan Threshold: PASS")
print("High DTI: PASS")
print("Employment Category: PASS")
print("Loan Boundary: PASS")
print("EMI Calculation: PASS")
print("Invalid Input: PASS")
print("Exception Handling: PASS")
